=== szopkopatrik/Egyetem/webtech/Hamlet/hamlet.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT play (author,title,br,act)>
<!ELEMENT br (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT act (title,descreotion,speech)>
<!ELEMENT descreotion (#PCDATA)>
<!ELEMENT speech (speaker,line,stagedir)>
<!ELEMENT stagedir (#PCDATA)>
<!ELEMENT speaker (#PCDATA)>
<!ELEMENT line (break)>
<!ELEMENT break (#PCDATA)>

=== szopkopatrik/Egyetem/webtech/Hamlet/hamlet.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="hamlet.css" type="text/css"?>
<!DOCTYPE play SYSTEM "hamlet.dtd">
    <play>
        <author>William Shakespeare</author>
        <title>The Tragedy of Hamlet, Prince of Denmark</title>
        <br></br>
        <act>
            <title>ACT I</title>
            <descreotion>SCENE V. Another part of the platform.</descreotion>
            <speech>
                <speaker>HAMLET</speaker>
                <line>
                    O all you host of heaven! O earth! What else?<break></break>
                    And shall I couple hell? O, fie! Hold, hold, my heart;<break></break>
                    And you, my sinews, grow not instant old,<break></break>
                    But bear me stiffly up. Remember thee!<break></break>
                    Ay, thou poor ghost, while memory holds a seat<break></break>
                    In this distracted globe. Remember thee!<break></break>
                    Yea, from the table of my memory<break></break>
                    I'll wipe away all trivial fond records,<break></break>
                    All saws of books, all forms, all pressures past,<break></break>
                    That youth and observation copied there;<break></break>
                    And thy commandment all alone shall live<break></break>
                    Within the book and volume of my brain,<break></break>
                    Unmix'd with baser matter: yes, by heaven!<break></break>
                    O most pernicious woman!<break></break>
                    O villain, villain, smiling, damned villain!<break></break>
                    My tables,&#x2014;meet it is I set it down,<break></break>
                    That one may smile, and smile, and be a villain;<break></break>
                    At least I'm sure it may be so in Denmark:<break></break>
                    <stagedir>Writing</stagedir><break></break>
                    So, uncle, there you are. Now to my word;<break></break>
                    It is 'Adieu, adieu! remember me.'<break></break>
                    I have sworn 't.<break></break>
                </line>
                <stagedir>Enter HORATIO and MARCELLUS</stagedir>
                <speaker>HORATIO</speaker>
                <line><stagedir>Within</stagedir> My lord, my lord,--</line>
                <speaker>MARCELLUS</speaker>
                <line><stagedir>Within</stagedir> Lord Hamlet,&#x2014;</line>
                <speaker>HORATIO</speaker>
                <line><stagedir>Within</stagedir> Heaven secure him!</line>
                <speaker>HAMLET</speaker>
                <line>So be it!</line>
                <speaker>HORATIO</speaker>
                <line><stagedir>Within</stagedir> Hillo, ho, ho, my lord!</line>
                <speaker>HAMLET</speaker>
                <line>Hillo, ho, ho, boy! come, bird, come.</line>
            </speech>
        </act>
    </play>
